/* Generated By:JavaCC: Do not edit this line. _1CParserConstants.java */
package ru.spb.awk.driver.for1c.parcer.cc._1C;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface _1CParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int S_NUMBER = 8;
  /** RegularExpression Id. */
  int FLOAT = 9;
  /** RegularExpression Id. */
  int INTEGER = 10;
  /** RegularExpression Id. */
  int DIGIT = 11;
  /** RegularExpression Id. */
  int K_FIELDS = 12;
  /** RegularExpression Id. */
  int K_INDEXES = 13;
  /** RegularExpression Id. */
  int K_RECORDLOCK = 14;
  /** RegularExpression Id. */
  int K_FILES = 15;
  /** RegularExpression Id. */
  int S_IDENTIFIER = 16;
  /** RegularExpression Id. */
  int LETTER = 17;
  /** RegularExpression Id. */
  int SPECIAL_CHARS = 18;
  /** RegularExpression Id. */
  int S_BIND = 19;
  /** RegularExpression Id. */
  int S_CHAR_LITERAL = 20;
  /** RegularExpression Id. */
  int S_QUOTED_IDENTIFIER = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<S_NUMBER>",
    "<FLOAT>",
    "<INTEGER>",
    "<DIGIT>",
    "\"\\\"Fields\\\"\"",
    "\"\\\"Indexes\\\"\"",
    "\"\\\"Recordlock\\\"\"",
    "\"\\\"Files\\\"\"",
    "<S_IDENTIFIER>",
    "<LETTER>",
    "<SPECIAL_CHARS>",
    "<S_BIND>",
    "<S_CHAR_LITERAL>",
    "<S_QUOTED_IDENTIFIER>",
  };

}
