/* Generated By:JavaCC: Do not edit this line. SQLParserConstants.java */
package ru.spb.awk.driver.for1c.parcer.cc.SQL;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SQLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int K_SELECT = 5;
  /** RegularExpression Id. */
  int K_FROM = 6;
  /** RegularExpression Id. */
  int K_AS = 7;
  /** RegularExpression Id. */
  int K_WHERE = 8;
  /** RegularExpression Id. */
  int K_AND = 9;
  /** RegularExpression Id. */
  int K_OR = 10;
  /** RegularExpression Id. */
  int S_OP = 11;
  /** RegularExpression Id. */
  int S_NUMBER = 12;
  /** RegularExpression Id. */
  int FLOAT = 13;
  /** RegularExpression Id. */
  int INTEGER = 14;
  /** RegularExpression Id. */
  int DIGIT = 15;
  /** RegularExpression Id. */
  int LINE_COMMENT = 16;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 17;
  /** RegularExpression Id. */
  int S_IDENTIFIER = 18;
  /** RegularExpression Id. */
  int LETTER = 19;
  /** RegularExpression Id. */
  int SPECIAL_CHARS = 20;
  /** RegularExpression Id. */
  int S_BIND = 21;
  /** RegularExpression Id. */
  int S_CHAR_LITERAL = 22;
  /** RegularExpression Id. */
  int S_QUOTED_IDENTIFIER = 23;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"SELECT\"",
    "\"FROM\"",
    "\"AS\"",
    "\"WHERE\"",
    "\"AND\"",
    "\"OR\"",
    "\"=\"",
    "<S_NUMBER>",
    "<FLOAT>",
    "<INTEGER>",
    "<DIGIT>",
    "<LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "<S_IDENTIFIER>",
    "<LETTER>",
    "<SPECIAL_CHARS>",
    "<S_BIND>",
    "<S_CHAR_LITERAL>",
    "<S_QUOTED_IDENTIFIER>",
    "\";\"",
    "\".\"",
    "\"*\"",
    "\",\"",
    "\".*\"",
  };

}
